# Generated by Django 5.2.4 on 2025-07-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=64, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Заголовок")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Named URL"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menu",
                        verbose_name="Меню",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu.menuitem",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["order", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("url__isnull", False),
                                models.Q(("url", ""), _negated=True),
                                ("named_url__isnull", True),
                            ),
                            models.Q(
                                ("named_url__isnull", False),
                                models.Q(("named_url", ""), _negated=True),
                                ("url__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="menuitem_exactly_one_link_set",
                    ),
                    models.UniqueConstraint(
                        fields=("menu", "parent", "title"),
                        name="menuitem_unique_siblings_title",
                    ),
                ],
            },
        ),
    ]
